import { Badge, Button, Card, CardBody, CardTitle, Row, Col } from "reactstrap";
import Head from "next/head";
import Feeds from "../../src/components/dashboard/Feeds";
import Map from "@/src/components/dashboard/Map";
import CamFeed from "@/src/components/CamFeed";

const Badges = () => {
  return (
    <div>

      <Head>
        <title>Vehicle Tracking - TN Police</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/***Map & Feed***/}
        <Row>
          <Col sm="12" lg="6" xl="7" xxl="8">
            <Map />
          </Col>
          <Col sm="12" lg="6" xl="5" xxl="4">
            <Feeds />
          </Col>
        </Row>

        {/* CCTV Cam Feeds */}
        {/* <Row>
          <Col class="d-flex flex-row justify-content-between">
            <CamFeed/>
            <CamFeed/>
            <CamFeed/> */}
            {/* <CamFeed/> */}
          {/* </Col> */}
          {/* <Col sm="12" lg="6" xl="5" xxl="4">
            <CamFeed/>
          </Col> */}
        {/* </Row> */}

        <div class="container">
          <div class="row gap-4">
            {/* <div class="col-sm"> */}
              <CamFeed/>
            {/* </div> */}
            {/* <div class="col-sm"> */}
              <CamFeed/>
            {/* </div> */}
            {/* <div class="col-sm"> */}
              <CamFeed/>
            {/* </div> */}
          </div>
        </div>
    </div>
  );
};

export default Badges;
