import React, { useState } from 'react';
import Head from "next/head";
import { Button, ButtonGroup, Card, CardBody, CardTitle, Row, Col } from 'reactstrap';
import VehicleDetails from '@/src/components/dashboard/VehicleDetails';
import CamFeed from '@/src/components/CamFeed';
import NumPlateTable from '@/src/components/dashboard/NumPlateTable';


const Cards = () => {
  return (
    <div>
        <Head>
        <title>Vehicle Search - TN Police</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/***Map & Feed***/}
      <Row>
          <Col sm="12" lg="6" xl="7" xxl="8">
            <NumPlateTable/>
          </Col>
          <Col sm="12" lg="6" xl="5" xxl="4">
            <VehicleDetails />
          </Col>
        </Row>
    </div>
  );
};

export default Cards;
