import React, { useState } from 'react';
import Head from "next/head";
import { Button, ButtonGroup, Card, CardBody, CardTitle, Row, Col } from 'reactstrap';
import VehicleDetails from '@/src/components/dashboard/VehicleDetails';
import CamFeed from '@/src/components/CamFeed';
import ProjectTables from '@/src/components/dashboard/ProjectTable';

function numberPlateRecords() {
  return (
    <div>
        <Head>
        <title>Vehicle Search - TN Police</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/***Map & Feed***/}
      <Row>
          <Col sm="12" lg="6" xl="7" xxl="8">
            <ProjectTables />
          </Col>
          <Col sm="12" lg="6" xl="5" xxl="4">
            <VehicleDetails />
          </Col>
        </Row>

        {/* CCTV Cam Feeds */}
        {/* <Row>
          <Col class="d-flex flex-row justify-content-between">
            <CamFeed/>
            <CamFeed/>
            <CamFeed/> */}
            {/* <CamFeed/> */}
          {/* </Col> */}
          {/* <Col sm="12" lg="6" xl="5" xxl="4">
            <CamFeed/>
          </Col> */}
        {/* </Row> */}

        <div class="container">
          <div class="row gap-4">
            {/* <div class="col-sm"> */}
              <CamFeed/>
            {/* </div> */}
            {/* <div class="col-sm"> */}
              <CamFeed/>
            {/* </div> */}
            {/* <div class="col-sm"> */}
              <CamFeed/>
            {/* </div> */}
          </div>
        </div>
    </div>
  )
}

export default numberPlateRecords